### ISSUE TITLE
Problem with a module / attribute in master

### ISSUE THREAD

**Issue by rollanddelorme** [lm2-poly/PeriPyDIC#28]
I don't understand the problem.
This is maybe a problem with the "import" after merging yesterday

File "../../pd_dic.py", line 66, in simulation 
ccm_class = IO.ccm.CCM_calcul(deck, pb_solver_class)
AttributeError: 'module' object has no attribute 'ccm'

**Comment by ilyasst** [comment]
It most likely is, I didnt test the CCM class. Let me check it.

**Comment by ilyasst** [comment]
Can you send me the command you were trying to run ? Also maybe dummy inputs if I cannot simply use the examples to try it?

**Comment by rollanddelorme** [comment]
Run the code with 1D elastic example

**Comment by ilyasst** [comment]
Solved in 090cfe5272cce164935effa0b6390b7b1f39ef04
